### ISSUE TITLE
sphinx-gallery

### ISSUE THREAD

**Issue by agramfort** [rflamary/POT#1]
you should use https://github.com/sphinx-gallery/sphinx-gallery to generate your example gallery.

you would have the notebooks for free with download links at the bottom of the page.

also you build the doc I had to comment out this in conf.py :

```
# sys.path.insert(0, os.path.abspath("../.."))
#sys.setrecursionlimit(1500)



# class Mock(MagicMock):
#     @classmethod
#     def __getattr__(cls, name):
#         return Mock()

# MOCK_MODULES = [ 'emd','ot.lp.emd']
# sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)
```

thanks for making these tools easily available !

**Comment by rflamary** [comment]
Hello thank you for the information I will definitely look at this for the documentation.

I know about this problem in the documentation but I had to use this to make it compile on readthedoc.

The build fails because  of difference between python 2 and 3 I spent a few hours making it work on readthedoc but couldnt make it compile locally...

Will get to it when I have the time.

**Comment by agramfort** [comment]
do you want help with sphinx-gallery?

**Comment by rflamary** [comment]
Yes it would be welcome.  I always liked the figures in the doc of scikit-learn but didn't know how to do that properly.

**Comment by rflamary** [comment]
we now a have a far better documentation on readthedoc with sphinx gallery enabled.
Note that in order to build the gallery one needs to comment the Mock class as discussed in  https://github.com/rflamary/POT/issues/1#issue-193065601.

This Mock class allows the readthedoc to compile the documentation without compiling the cython extensions.

Thank you again to @agramfort  for helping us on this issue.

Rémi

**Comment by agramfort** [comment]
great !
