### ISSUE TITLE
Use target class proportions in transport.

### ISSUE THREAD

**Issue by tardyb** [rflamary/POT#60]
Hi,

I want to use the sinkhorn transport and the two regularization method), with different estimation of the target class proportions, similar to the work done here [https://hal.archives-ouvertes.fr/hal-01254329/file/OT-multitemp2015-paper.pdf](https://hal.archives-ouvertes.fr/hal-01254329/file/OT-multitemp2015-paper.pdf).
For now, the only estimation available is the uniform one, if I not missed something.
In the deprecated classes as OTDA_lpl1, it is possible to custom the weights used (with the ws parameter).
So my questions are:
1. Why the current transport classes no longer allow the use of customised weights?
2. There are other classes allowing using these parameters?
3. There is any kind of issue on the transport estimation by using estimated proportions?

Best regards,
Benjamin.

**Comment by rflamary** [comment]
Hello @tardyb,

The new classes do not take as parameter the weights of the samples indeed but they have the parameter ```distribution_estimation``` that take a matrix in output an return the weights of the samples. This function allows more general stuff and replaced those parameters.

You can define the weights of the samples (corrected or not) by defining something as
```python
ws,wt= # weights for source and target samples
xs, xt = # sample matrices
def distribution_estimation(x):
    return ws if x is xs else wt
```
and use the defined function in the new classes. All the new class can do that and use these function to return weights.

Your last point is more complex since there will be problems depending on how well you can estimate the target class proportions.To the best of my knowledge estimating class proportion in a DA setting is still an open problem. We have been working on this problem with Ivgen Redko on the multi-domain setting in the following paper:
https://arxiv.org/pdf/1803.04899.pdf
It can be extended to more general DA problems (other than target shift) but we haven't tried yet.

**Comment by tardyb** [comment]
Hi, 
thank you for your complete answer.
I've looked only the comments in the da.py file and didn't notice that parameter is a function... My mistake. I'll test soon to use it, so I close this issue. 
Thank you for the reference, it will be useful. 

Bests.
