### ISSUE TITLE
Usage of ot.gpu

### ISSUE THREAD

**Issue by yanghtr** [rflamary/POT#61]
hi, 
I search the full document [https://pot.readthedocs.io/en/latest/index.html](url) but I can not find any usage information about  `ot.gpu`.
I wonder whether there is some document or example about the usage of `ot.gpu`
Thanks

**Comment by rflamary** [comment]
Hello @yanghtr,

We indeed have no proper documentation for ot.gpu but the functions are all properly documented in the code. An exaple of their use can be seen here:
https://github.com/rflamary/POT/blob/master/test/test_gpu.py

In practice, the classesd and fuinction have been coded to be compatible with ot.sinkhorn and classes in ot.da.

Also note that ot.gpu depends on cudamat that is a library that is not developped anymore and we will prpbably deprecate it in the future.  A nice pull request has been proposed using the more recent cupy 
https://github.com/rflamary/POT/pull/32 but we cannot merge it yet  because it is still slower that ot.gpu and introduce documentation problems on the rest of the pot toolbox.

**Comment by yanghtr** [comment]
Thanks for your kind reply!
